Milo/add jwt auth for services
kiwicom/iam pull request #349
Opened 2022-03-07 12:51 UTC by ArcHound

This new feature enables authorization via GoogleID tokens and Gitlab CI/CD JWT tokens.

2022-03-07 16:34 UTC, vavkamil commented on Makefile
> +lint: revive-lint # golangci-lint
Why is `golangci-lint` going to be removed?

2022-03-07 16:40 UTC, vavkamil commented on internal/security/secrets/json_file.go
> +	log.Printf("Synced %v settings, %v tokens, %v google IDs and %v gitlab claims.", len(s.settings), len(s.tokens), len(s.googleIds), len(s.gitlabClaims))
```suggestion
	log.Printf("Synced %v settings, %v tokens, %v Google IDs and %v GitLab claims.", len(s.settings), len(s.tokens), len(s.googleIds), len(s.gitlabClaims))
```

2022-03-07 16:43 UTC, vavkamil commented on internal/security/secrets/local.go
> +	gitlabAllowlistVar := "GITLABCLAIM_ALLOWLIST"
Where is `GITLABCLAIM_ALLOWLIST` defined?

2022-03-07 16:49 UTC, vavkamil commented on internal/security/validate_token.go
> +	if exp.Before(time.Now()) {
Is this timestamp, or is it possible that the timezone for `Kiwi IAM` and `GitLab` is different?

2022-03-07 16:51 UTC, vavkamil commented on internal/security/validate_token.go
>  var errUnathorised = errors.New("incorrect token")
```suggestion
var errUnauthorised = errors.New("incorrect token")
```

2022-03-07 16:52 UTC, vavkamil commented on internal/security/validate_token.go
>  		return errUnathorised
```suggestion
		return errUnauthorised
```

2022-03-07 16:52 UTC, vavkamil commented on internal/security/validate_token.go
> +		return errUnathorised
```suggestion
		return errUnauthorised
```

2022-03-07 16:52 UTC, vavkamil commented on internal/security/validate_token.go
> +		return errUnathorised
```suggestion
		return errUnauthorised
```

2022-03-07 16:52 UTC, vavkamil commented on internal/security/validate_token.go
> +		return errUnathorised
```suggestion
		return errUnauthorised
```

2022-03-07 16:53 UTC, vavkamil commented on internal/security/validate_token.go
> +		return errUnathorised
```suggestion
		return errUnauthorised
```

2022-03-07 16:53 UTC, vavkamil commented on internal/security/validate_token.go
> +		return errUnathorised
```suggestion
		return errUnauthorised
```

2022-03-07 16:53 UTC, vavkamil commented on internal/security/validate_token.go
> +	return errUnathorised
```suggestion
	return errUnauthorised
```

2022-03-07 17:16 UTC, aexvir commented on api/rest/v1/middleware_security_test.go
> +}
same here

2022-03-07 17:22 UTC, aexvir commented on internal/security/secrets/json_file.go
> +	GoogleIDs []string `json:"google_ids"`
you didn't run `gofmt`
```bash
gofmt -w .
```

2022-03-07 17:34 UTC, aexvir commented on internal/security/secrets/json_file.go
> +		_, err := ioutil.ReadFile(p)
if you're going to ignore the file content that's pretty much checking for file existance
in that case I'd say you should use `os.Stat` instead, to avoid unnecessary file reads

2022-03-07 17:45 UTC, aexvir commented on internal/security/secrets/json_file.go
> +		paths:      paths,
after reading more code below it seems that you'd rather have a slice of jsonfilemanagers? because all the data is being overwritten within the loop over paths...

tbh I don't understand this change nor how it's related to the jwt auth for services

it's also not documented so I don't even know how it's supposed to work... it's a bit hard to review at this moment

2022-03-07 17:46 UTC, aexvir requested changes
besides all the previous comments, please run the basics; fmt, tests and linters
avoid disabling linters just because they're not passing
and clean up the commits so they're meaningful, as right now it's quite messy and hard to understand what this merge request is trying to do

adding some more info to the pr description would do wonders as well

2022-03-08 08:12 UTC, ArcHound commented on Makefile
> +lint: revive-lint # golangci-lint
There are several reasons:
 - it disallows code that wasn't changed at all (inconsistent rules in time)
 - it has a sketchy installation process (download a binary, go install is not recommended)
 - we already have a linter, why would we need two? This would only create conflicts.

2022-03-08 08:14 UTC, ArcHound commented on internal/security/validate_token.go
> +	if exp.Before(time.Now()) {
This is a timestamp. Yes, I am worried about esoteric timezone bugs too.

2022-03-08 08:21 UTC, ArcHound commented on internal/security/secrets/json_file.go
> +		_, err := ioutil.ReadFile(p)
I disagree, I need to verify that it is possible to read from that file (but yes, I didn't want to mess with the filesystem permissions).

2022-03-08 08:25 UTC, ArcHound commented on internal/security/secrets/json_file.go
> +		paths:      paths,
In the original version, there was a bug causing secrets not to sync as the file would be read into memory and then checked whether something in that memory would change (it wouldn't). So the solution was to store the path of the file and read from that file when secrets are to be synced. Rather than creating a separate branch, I decided to fix this bug silently as no one else noticed.

2022-03-08 08:30 UTC, ArcHound commented on internal/security/secrets/json_file.go
> +	GoogleIDs []string `json:"google_ids"`
Yes, I did not.

2022-03-08 08:31 UTC, ArcHound commented on internal/security/secrets/json_file.go
> +		gitlabClaims: make([]string, 0),
I decided against a heavy constructor - that would require reading and parsing all of the files in paths, some of which may not exist at all.

2022-03-08 08:32 UTC, ArcHound commented on internal/security/secrets/json_file.go
> +		gitlabClaims: make([]string, 0),
So no, at that point I do not know the length of those slices.

2022-03-08 08:34 UTC, ArcHound commented on internal/security/secrets/json_file.go
> +		s.raw = data
yes, it would be prettier if the raw wasn't in the object definition. Will refactor this.

2022-03-08 08:35 UTC, ArcHound commented on internal/security/secrets/json_file.go
> +		s.settings = secrets.Settings
now, this is bad, thank you.

2022-03-08 08:44 UTC, ArcHound commented on internal/security/secrets/json_file.go
> +		s.googleIds = append(s.googleIds, secrets.GoogleIDs...)
no, it appends https://go.dev/tour/moretypes/15

2022-03-08 09:02 UTC, ArcHound commented on api/rest/v1/middleware_security_test.go
> +}
Thank you for your suggestion, I'll do that another time.

2022-03-08 09:02 UTC, ArcHound commented on api/rest/v1/middleware_security_test.go
> +}
Thank you for your suggestion, I'll do that another time.

2022-03-08 09:03 UTC, ArcHound commented on internal/security/secrets/json_file.go
> +	GoogleIDs []string `json:"google_ids"`
Fixed in the current commit

2022-03-08 09:03 UTC, ArcHound commented on internal/security/secrets/json_file.go
> +		s.raw = data
Fixed in the current commit.

2022-03-08 09:18 UTC, ArcHound commented
To @aexvir 

Thank you for finding the time to read the code. To reply to your comment:

> besides all the previous comments, please run the basics; fmt, tests and linters 
I did.

> avoid disabling linters just because they're not passing 
I still stand by this change. Two linters are not better than one, moreover code that used to pass started failing so I would need to refactor the whole codebase. 

> and clean up the commits so they're meaningful, as right now it's quite messy and hard to understand what this merge request is trying to do
Commits will be squashed anyway, but yes, they were quite messy.

> adding some more info to the pr description would do wonders as well
I apologize here - I had no idea that somebody else would read this. Our team was updated in the internal channels.

2022-03-08 09:22 UTC, ArcHound reviewed
All of the issues should be resolved by now (in one way or another).

2022-03-08 10:04 UTC, aexvir commented
> I still stand by this change. Two linters are not better than one, moreover code that used to pass started failing, so I would need to refactor the whole codebase.

`golangci-lint` is not a linter on it's own, but a collection of linters; which actually includes revive
I completely disagree with disabling golangci-lint here only because one of the linters might not be passing, and this is a no-no from my side to merge this tbh

the biggest issue I see on this mr is that is doing too many things; if you wouldn't have updated dependencies here you woulnd't have issues with the linter failing to pass because the newer version of golangci-lint (or one of its linters) now checks for more things

you can still pin the linter to an older version and keep it enabled; then tackle the linter upgrade on a different pr

2022-03-08 10:06 UTC, aexvir commented
> Commits will be squashed anyway, but yes, they were pretty messy.
that's not the point though... any reviewer needs to understand the pr in order to do a good review, and the commits are the main communication from your side, and this is just a mess right now

too many changes on a single pr is usually challenging to review, but at least having meaningful commits can help the reviewer navigate the changes

and tbh I'd be completely against squashing all this commits... you're doing more stuff here than just adding jwt auth for services as the pr is claiming; stuff like the dependency updates have no point here and it will just make the blame messier

2022-03-08 10:15 UTC, aexvir commented on internal/security/secrets/json_file.go
> +		s.googleIds = append(s.googleIds, secrets.GoogleIDs...)
first: please don't resolve conversationsl, that's usually up to the reviewer, once the fix is accepted
second: your comment doesn't say anything?

the problem I'm exposing here is that in the case that paths has more than one element, you're appending to `s.googleIds` the same potential `secrets.GoogleIDs` multiple times, ending with duplicated data

like this: https://goplay.space/#LnxGv3Y8Se_K

yesterday I didn't realize that the secrets are loaded from the file though, so this is not that big of an issue, but I'd still probably handle duplicates here, as it could cause issues down the line

2022-03-08 16:25 UTC, aexvir commented
closing in favor of #352

2022-03-08 16:25 UTC, closed without merging